class HebrewLetterInfo {
  final String letter;
  final String name;
  final String nameRu;
  final String meaning;
  final String meaningRu;
  final String symbol;
  final String symbolRu;
  final String function;
  final String functionRu;

  const HebrewLetterInfo({
    required this.letter,
    required this.name,
    required this.nameRu,
    required this.meaning,
    required this.meaningRu,
    required this.symbol,
    required this.symbolRu,
    required this.function,
    required this.functionRu,
  });
}

const Map<String, HebrewLetterInfo> hebrewLetters = {
  'א': HebrewLetterInfo(
    letter: 'א',
    name: 'Aleph',
    nameRu: 'Алеф',
    meaning: 'Source, Unity, Energy',
    meaningRu: 'Источник, Единство, Энергия',
    symbol: 'Pure Will, Quantum Field',
    symbolRu: 'Чистая воля, Квантовое поле',
    function: 'Start of process, impulse from the "cloud".',
    functionRu: 'Начало процесса, импульс из «облака».',
  ),
  'ב': HebrewLetterInfo(
    letter: 'ב',
    name: 'Bet',
    nameRu: 'Бет',
    meaning: 'House, Vessel, Structure',
    meaningRu: 'Дом, Сосуд, Структура',
    symbol: 'Container, Shell',
    symbolRu: 'Контейнер, Оболочка',
    function: 'Creating form, stabilizing data.',
    functionRu: 'Создание формы, стабилизация данных.',
  ),
  'ג': HebrewLetterInfo(
    letter: 'ג',
    name: 'Gimel',
    nameRu: 'Гимел',
    meaning: 'Camel, Movement, Reward',
    meaningRu: 'Верблюд, Движение, Вознаграждение',
    symbol: 'Bridge, Transport',
    symbolRu: 'Мост, Транспорт',
    function: 'Transfer of resources, crossing barriers.',
    functionRu: 'Перенос ресурсов, преодоление барьеров.',
  ),
  'ד': HebrewLetterInfo(
    letter: 'ד',
    name: 'Dalet',
    nameRu: 'Далет',
    meaning: 'Door, Humility, Access',
    meaningRu: 'Дверь, Смирение, Доступ',
    symbol: 'Gateway, Threshold',
    symbolRu: 'Врата, Порог',
    function: 'Opening access, entry point to a new level.',
    functionRu: 'Открытие доступа, точка входа на новый уровень.',
  ),
  'ה': HebrewLetterInfo(
    letter: 'ה',
    name: 'Hey',
    nameRu: 'Гей',
    meaning: 'Window, Breath, Self-expression',
    meaningRu: 'Окно, Дыхание, Самовыражение',
    symbol: 'Opening, Energy Release',
    symbolRu: 'Просвет, Выход энергии',
    function: 'Transmitting data to the outer world, "release".',
    functionRu: 'Передача данных во внешний мир, «релиз».',
  ),
  'ו': HebrewLetterInfo(
    letter: 'ו',
    name: 'Vav',
    nameRu: 'Вав',
    meaning: 'Hook, Connection, Channel',
    meaningRu: 'Крючок, Связь, Канал',
    symbol: 'Vertical Line, Connector',
    symbolRu: 'Вертикальная линия, Коннектор',
    function: 'Connecting two points (Heaven and Earth, you and them).',
    functionRu: 'Соединение двух точек (Неба и Земли, тебя и его).',
  ),
  'ז': HebrewLetterInfo(
    letter: 'ז',
    name: 'Zayin',
    nameRu: 'Заин',
    meaning: 'Sword, Struggle, Purpose',
    meaningRu: 'Меч, Борьба, Цель',
    symbol: 'Weapon, Sharp Edge',
    symbolRu: 'Оружие, Острый край',
    function: 'Cutting through obstacles, focused effort.',
    functionRu: 'Прорубание препятствий, сфокусированное усилие.',
  ),
  'ח': HebrewLetterInfo(
    letter: 'ח',
    name: 'Chet',
    nameRu: 'Хет',
    meaning: 'Fence, Life Force, Protection',
    meaningRu: 'Забор, Жизненная сила, Защита',
    symbol: 'Enclosure, Shield',
    symbolRu: 'Ограждение, Щит',
    function: 'Protection of inner space, life energy boundary.',
    functionRu: 'Защита внутреннего пространства, граница жизненной энергии.',
  ),
  'ט': HebrewLetterInfo(
    letter: 'ט',
    name: 'Tet',
    nameRu: 'Тет',
    meaning: 'Serpent, Hidden Good, Potential',
    meaningRu: 'Змея, Скрытое добро, Потенциал',
    symbol: 'Coiled Energy, Vessel of Good',
    symbolRu: 'Свёрнутая энергия, Сосуд добра',
    function: 'Concealed potential waiting to be revealed.',
    functionRu: 'Скрытый потенциал, ожидающий раскрытия.',
  ),
  'י': HebrewLetterInfo(
    letter: 'י',
    name: 'Yud',
    nameRu: 'Йуд',
    meaning: 'Point, Seed, Intellect',
    meaningRu: 'Точка, Семя, Интеллект',
    symbol: 'Spark, Initial Bit',
    symbolRu: 'Искра, Начальный бит',
    function: 'Concentrating power in a single point. Minimalism.',
    functionRu: 'Концентрация силы в одной точке. Минимализм.',
  ),
  'כ': HebrewLetterInfo(
    letter: 'כ',
    name: 'Kaf',
    nameRu: 'Каф',
    meaning: 'Palm, Potential, Bending',
    meaningRu: 'Ладонь, Потенциал, Сгибание',
    symbol: 'Open Hand, Receiver',
    symbolRu: 'Открытая рука, Приёмник',
    function: 'Receiving and shaping energy, potential into form.',
    functionRu: 'Приём и формирование энергии, потенциал в форму.',
  ),
  'ל': HebrewLetterInfo(
    letter: 'ל',
    name: 'Lamed',
    nameRu: 'Ламед',
    meaning: 'Learning, Direction, Purpose',
    meaningRu: 'Обучение, Направление, Цель',
    symbol: 'Wing, Reaching Beyond',
    symbolRu: 'Крыло, Выход за пределы',
    function: 'Expanding the system, aspiring upward.',
    functionRu: 'Расширение системы, стремление вверх.',
  ),
  'מ': HebrewLetterInfo(
    letter: 'מ',
    name: 'Mem',
    nameRu: 'Мем',
    meaning: 'Water, Matrix, Mother',
    meaningRu: 'Вода, Матрица, Мать',
    symbol: 'Flow, Vibration, Cycle',
    symbolRu: 'Поток, Вибрация, Цикл',
    function: 'Transformation, depth of feelings, "Runtime".',
    functionRu: 'Трансформация, глубина чувств, «Runtime».',
  ),
  'נ': HebrewLetterInfo(
    letter: 'נ',
    name: 'Nun',
    nameRu: 'Нун',
    meaning: 'Fish, Life, Movement',
    meaningRu: 'Рыба, Жизнь, Движение',
    symbol: 'Flexibility, Fluidity',
    symbolRu: 'Гибкость, Текучесть',
    function: 'Energy in motion, overcoming stagnation.',
    functionRu: 'Энергия в динамике, преодоление застоя.',
  ),
  'ס': HebrewLetterInfo(
    letter: 'ס',
    name: 'Samekh',
    nameRu: 'Самех',
    meaning: 'Support, Cyclicity, Trust',
    meaningRu: 'Поддержка, Цикличность, Доверие',
    symbol: 'Circle, Endless Loop',
    symbolRu: 'Круг, Бесконечный цикл',
    function: 'Support structure, trust in the process.',
    functionRu: 'Структура поддержки, доверие процессу.',
  ),
  'ע': HebrewLetterInfo(
    letter: 'ע',
    name: 'Ayin',
    nameRu: 'Аин',
    meaning: 'Eye, Vision, Analysis',
    meaningRu: 'Глаз, Видение, Анализ',
    symbol: 'Observer, Lens',
    symbolRu: 'Наблюдатель, Объектив',
    function: 'Recognizing truth, "Debug" of reality.',
    functionRu: 'Распознавание правды, «Debug» реальности.',
  ),
  'פ': HebrewLetterInfo(
    letter: 'פ',
    name: 'Pey',
    nameRu: 'Пей',
    meaning: 'Mouth, Word, Speech',
    meaningRu: 'Рот, Слово, Речь',
    symbol: 'Output Interface',
    symbolRu: 'Выходной интерфейс',
    function: 'Materializing thought through sound/word.',
    functionRu: 'Материализация мысли через звук/слово.',
  ),
  'צ': HebrewLetterInfo(
    letter: 'צ',
    name: 'Tsadi',
    nameRu: 'Цади',
    meaning: 'Righteousness, Hunting, Justice',
    meaningRu: 'Праведность, Охота, Справедливость',
    symbol: 'Hook, Anchor',
    symbolRu: 'Крюк, Якорь',
    function: 'Pursuing justice, catching the right signal.',
    functionRu: 'Стремление к справедливости, захват нужного сигнала.',
  ),
  'ק': HebrewLetterInfo(
    letter: 'ק',
    name: 'Qof',
    nameRu: 'Куф',
    meaning: 'Back of Head, Holiness, Cycle',
    meaningRu: 'Затылок, Святость, Цикл',
    symbol: 'Eye of Needle, Hidden Sight',
    symbolRu: 'Игольное ушко, Скрытое зрение',
    function: 'Accessing hidden layers, deep processing.',
    functionRu: 'Доступ к скрытым слоям, глубокая обработка.',
  ),
  'ר': HebrewLetterInfo(
    letter: 'ר',
    name: 'Resh',
    nameRu: 'Реш',
    meaning: 'Head, Beginning, Summit',
    meaningRu: 'Голова, Начало, Вершина',
    symbol: 'Control, Processor',
    symbolRu: 'Управление, Процессор',
    function: 'Leadership, shifting the mental paradigm.',
    functionRu: 'Лидерство, смена ментальной парадигмы.',
  ),
  'ש': HebrewLetterInfo(
    letter: 'ש',
    name: 'Shin',
    nameRu: 'Шин',
    meaning: 'Fire, Transformation',
    meaningRu: 'Огонь, Трансформация',
    symbol: 'Teeth, Flame, Energy',
    symbolRu: 'Зубья, Пламя, Энергия',
    function: 'Drastic change, "burning" old code.',
    functionRu: 'Резкое изменение, «сжигание» старого кода.',
  ),
  'ת': HebrewLetterInfo(
    letter: 'ת',
    name: 'Tav',
    nameRu: 'Тав',
    meaning: 'Sign, Truth, Completion',
    meaningRu: 'Знак, Истина, Завершение',
    symbol: 'Seal, Final Mark',
    symbolRu: 'Печать, Финальная метка',
    function: 'Completion of the cycle, sealing the result.',
    functionRu: 'Завершение цикла, запечатывание результата.',
  ),
};
